version: '3.7'
services:
  productservice:
    image: app/product-service:0.0.1-SNAPSHOT
    ports:
      - "80:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "product-service"
networks:
  backend:
    driver: bridge