version: '3'
services:
  oracle:
    image: gvenzl/oracle-xe:11.2.0.2-slim
    restart: always
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: hta
      APP_USER_PASSWORD: zxcv1234
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - oracle-data:/u01/app/oracle/oradata
    networks:
      - backend
  configserver:
    image: app/config-server:0.0.1-SNAPSHOT
    ports:
      - '8071:8071'
    environment:
      - "ENCRYPT_KEY=a4f397d68e7b9aa21692e49451bda3981a29e292399a82f7c3cdea44259a9b4c"
    networks:
      - backend
    profiles:
      - app
  productservice:
    image: app/product-service:0.0.1-SNAPSHOT
    ports:
      - "80:8080"
    networks:
      backend:
    depends_on:
      - oracle
      - configserver
    restart: always
    profiles:
      - app
networks:
  backend:
    driver: bridge
volumes:
  oracle-data: