logging:
  level:
    '[com.example.product.repository]': debug
spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://configserver:8071
      name: product-service      